FROM hhkhanh/tips_image:raw

RUN pip install jupyterlab

RUN chmod +x /TIPs/initialize.sh

EXPOSE 8888

CMD ["/bin/bash", "-c", "/TIPs/initialize.sh && jupyter lab \
  --ip=0.0.0.0 \
  --port=8888 \
  --no-browser \
  --allow-root \
  --ServerApp.token='' \
  --ServerApp.password='' \
  --ServerApp.allow_origin='*' \
  --ServerApp.allow_remote_access=True \
  --ServerApp.tornado_settings='{\"headers\": {\"Content-Security-Policy\": \"frame-ancestors *\"}}'"]
