FROM hhkhanh/tips_image:raw

USER root

RUN pip install --quiet --no-cache-dir gdown \
 && gdown "1UuFgZ-kwRryPC-vK7w64xX0VO4iOAeGt" -O /tmp/nnResults.zip \
 && mkdir -p /tmp/nnResults_unzipped \
 && python -m zipfile -e /tmp/nnResults.zip /tmp/nnResults_unzipped \
 && rm -rf /tmp/nnResults.zip \
 && mv /tmp/nnResults_unzipped/nnResults /TIPs/nnResults \
 && rm -rf /tmp/nnResults_unzipped