name: Build Raw Image

on:
  workflow_dispatch:
    inputs:
      docker_user:
        description: "Docker Hub username (optional override)"
        required: false
      docker_pat:
        description: "Docker Hub PAT (optional override)"
        required: false
      buildx_endpoint:
        description: "Docker Buildx cloud endpoint (e.g. org/builder)"
        required: false
        default: "hhkhanh/tips"

  push:
    branches:
      - "build_raw_image"

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ github.event.inputs.docker_user || secrets.DOCKER_USER }}
      DOCKER_PAT: ${{ github.event.inputs.docker_pat || secrets.DOCKER_PAT }}
      BUILDX_ENDPOINT: ${{ github.event.inputs.buildx_endpoint || 'hhkhanh/tips' }}

    steps:
      - name: Print env variables
        run: |
          echo "DOCKER_USER=$DOCKER_USER"
          echo "BUILDX_ENDPOINT=$BUILDX_ENDPOINT"
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: ${{ env.BUILDX_ENDPOINT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          tags: "${{ env.DOCKER_USER }}/tips_image:raw"
          push: true
