name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which image to build"
        required: true
        type: choice
        options:
          - raw
          - inference
          - serverless
          - all

jobs:
  build-raw:
    if: ${{ inputs.target == 'raw' || inputs.target == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "hhkhanh/tips"
      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          tags: "${{ vars.DOCKER_USER }}/tips_image:raw"
          push: true

  build-inference:
    if: ${{ inputs.target == 'inference' || inputs.target == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "hhkhanh/tips"
      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.inference
          tags: "${{ vars.DOCKER_USER }}/tips_image:inference"
          push: true

  build-serverless:
    if: ${{ inputs.target == 'serverless' || inputs.target == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "hhkhanh/tips"
      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.severless
          tags: "${{ vars.DOCKER_USER }}/tips_image:serverless"
          push: true
